Se refactorizan flujos para solicitud entrevista
EntrevistadorInteligente/si-orchestrator pull request #22
Opened 2024-04-13 16:00 UTC by JamiltonQuintero2

## TL;DR

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-04-13 19:50 UTC, Kirenai commented
Las Clases en Test SolicitudEntrevistaServiceTest y ActualizarInformacionEntrevistaServiceTest, tienen problemas.

2024-04-13 19:52 UTC, Kirenai requested changes
Realizar los cambios mencionados y explicar otros.

2024-04-13 19:52 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/infrastructure/adapter/jms/JmsPublisherAdapter.java
> +    private String topicValidador;
No se está utilizando esta variable de instancia, será para un futuro?

2024-04-13 19:52 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/dominio/model/dto/RagsIdsDto.java
> +    boolean isIsHojaDeVidaValida();
Doble "is" "Is", es seguro llamarlo de aquella manera?

2024-04-13 19:52 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/dominio/port/client/AnalizadorClient.java
> +import com.entrevistador.orquestador.dominio.model.dto.*;
Evitar la importación de todo el paquete.
En el discord en el chat de orquestador hay una forma de evitar que el IDE realize la importación por "*".

2024-04-13 19:52 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/infrastructure/adapter/repository/EntrevistaRepository.java
> +    Mono<RagsIdsDto> findIdHojaDeVidaAndInformacionEmpresaAndEsHojaDeVidaValidaIdById(String id);
Agregar el By luego del find
```suggestion
    Mono<RagsIdsDto> findByIdHojaDeVidaAndInformacionEmpresaAndEsHojaDeVidaValidaIdById(String id);
```

2024-04-13 19:52 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/infrastructure/beanconfiguration/KafkaConfiguration.java
> +    private String topicValidador;
No se está utilizando esta variable de instancia, será para un futuro?

2024-04-13 19:52 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/infrastructure/rest/controller/EntrevistaController.java
> +            @RequestParam String username,
Si no se envía nada en el username, puede que cause problemas al llegar al Repository de la Colección en uso.

2024-04-13 22:30 UTC, Kirenai commented
Como se esta quitando el paquete port.client. Eliminar la Clase WebClientConfig.

2024-04-16 14:12 UTC, JamiltonQuintero2 commented on src/main/java/com/entrevistador/orquestador/infrastructure/adapter/jms/JmsPublisherAdapter.java
> +    private String topicValidador;
Corregido

2024-04-16 14:36 UTC, JamiltonQuintero2 commented on src/main/java/com/entrevistador/orquestador/infrastructure/adapter/repository/EntrevistaRepository.java
> +    Mono<RagsIdsDto> findIdHojaDeVidaAndInformacionEmpresaAndEsHojaDeVidaValidaIdById(String id);
el find by esta al final se cambia a español para ser ,ams descriptivo ya que es una projections con @quuiery que no necesita nomenclatura de jpa

2024-04-19 13:54 UTC, JamiltonQuintero2 commented on src/main/java/com/entrevistador/orquestador/infrastructure/rest/controller/EntrevistaController.java
> +            @RequestParam String username,
Este de momento tomemoslo como un caso muy de borde que quizas no pueda pasar. Esa ruta es ruita protegida por keykloak. El username se saca del token y se manda por param. Si no llega lo que pasaria es que no encutnra rags de la hoja de vida en lo steps siguientes y no genera entrevistas.

2024-04-20 00:16 UTC, Kirenai approved these changes

2024-04-20 00:16 UTC, merged