Se agrega dtpo respuesta para confirmacion o body sin response
EntrevistadorInteligente/si-orchestrator pull request #47
Opened 2024-06-08 02:17 UTC by JamiltonQuintero

## TL;DR

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-06-08 02:38 UTC, Kirenai requested changes
Hacer las modificaciones en el test.

2024-06-08 02:38 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/infrastructure/rest/controller/EntrevistaController.java
Un test unitario fallo en:
EntrevistaControllerTest.shouldLoadCV_WhenPost

2024-06-09 19:36 UTC, JamiltonQuintero commented on src/main/java/com/entrevistador/orquestador/infrastructure/rest/controller/EntrevistaController.java
Listo señor

2024-06-10 00:05 UTC, Kirenai approved these changes

2024-06-10 00:05 UTC, merged