Llamada sincrona cv
EntrevistadorInteligente/si-orchestrator pull request #52
Opened 2024-06-29 03:04 UTC by JamiltonQuintero

## TL;DR

Closes # 

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-07-04 00:22 UTC, Kirenai requested changes

2024-07-04 00:22 UTC, Kirenai commented on src/main/java/com/entrevistador/orquestador/infrastructure/adapter/jms/JmsListenerAdapter.java
> +    private final EntrevistaMapper mapperEntrevista;
Se inyecta, pero se está usando?

2024-07-08 00:22 UTC, JamiltonQuintero commented on src/main/java/com/entrevistador/orquestador/infrastructure/adapter/jms/JmsListenerAdapter.java
> +    private final EntrevistaMapper mapperEntrevista;
Corregido papu

2024-07-08 21:29 UTC, Kirenai approved these changes

2024-07-08 21:29 UTC, merged